version: '3.7'

services:
    radio:
        build: .
        command: gunicorn api:create_app() --bind 0.0.0.0:8000
        expose:
            - 8000
    nginx:
        image: nginx:latest
        ports:
            - 8000:8000
